// Country centroids for the 3D globe (approximate lat/lng of country center)
export const COUNTRIES = [
  { code: 'US', name: 'United States', lat: 39.8, lng: -98.6 },
  { code: 'CA', name: 'Canada', lat: 56.1, lng: -106.3 },
  { code: 'MX', name: 'Mexico', lat: 23.6, lng: -102.6 },
  { code: 'BR', name: 'Brazil', lat: -14.2, lng: -51.9 },
  { code: 'AR', name: 'Argentina', lat: -38.4, lng: -63.6 },
  { code: 'CL', name: 'Chile', lat: -35.7, lng: -71.5 },
  { code: 'CO', name: 'Colombia', lat: 4.6, lng: -74.3 },
  { code: 'PE', name: 'Peru', lat: -9.2, lng: -75.0 },
  { code: 'VE', name: 'Venezuela', lat: 6.4, lng: -66.6 },
  { code: 'GB', name: 'United Kingdom', lat: 55.4, lng: -3.4 },
  { code: 'IE', name: 'Ireland', lat: 53.4, lng: -8.2 },
  { code: 'FR', name: 'France', lat: 46.6, lng: 2.2 },
  { code: 'DE', name: 'Germany', lat: 51.2, lng: 10.4 },
  { code: 'ES', name: 'Spain', lat: 40.5, lng: -3.7 },
  { code: 'PT', name: 'Portugal', lat: 39.4, lng: -8.2 },
  { code: 'IT', name: 'Italy', lat: 41.9, lng: 12.6 },
  { code: 'NL', name: 'Netherlands', lat: 52.1, lng: 5.3 },
  { code: 'BE', name: 'Belgium', lat: 50.5, lng: 4.5 },
  { code: 'CH', name: 'Switzerland', lat: 46.8, lng: 8.2 },
  { code: 'AT', name: 'Austria', lat: 47.5, lng: 14.6 },
  { code: 'SE', name: 'Sweden', lat: 60.1, lng: 18.6 },
  { code: 'NO', name: 'Norway', lat: 60.5, lng: 8.5 },
  { code: 'DK', name: 'Denmark', lat: 56.3, lng: 9.5 },
  { code: 'FI', name: 'Finland', lat: 61.9, lng: 25.7 },
  { code: 'PL', name: 'Poland', lat: 51.9, lng: 19.1 },
  { code: 'CZ', name: 'Czechia', lat: 49.8, lng: 15.5 },
  { code: 'GR', name: 'Greece', lat: 39.1, lng: 21.8 },
  { code: 'RO', name: 'Romania', lat: 45.9, lng: 24.9 },
  { code: 'UA', name: 'Ukraine', lat: 48.4, lng: 31.2 },
  { code: 'RU', name: 'Russia', lat: 61.5, lng: 105.3 },
  { code: 'TR', name: 'Turkey', lat: 39.0, lng: 35.2 },
  { code: 'IL', name: 'Israel', lat: 31.0, lng: 34.9 },
  { code: 'SA', name: 'Saudi Arabia', lat: 23.9, lng: 45.1 },
  { code: 'AE', name: 'United Arab Emirates', lat: 23.4, lng: 53.8 },
  { code: 'QA', name: 'Qatar', lat: 25.4, lng: 51.2 },
  { code: 'EG', name: 'Egypt', lat: 26.8, lng: 30.8 },
  { code: 'ZA', name: 'South Africa', lat: -30.6, lng: 22.9 },
  { code: 'NG', name: 'Nigeria', lat: 9.1, lng: 8.7 },
  { code: 'KE', name: 'Kenya', lat: -0.0, lng: 37.9 },
  { code: 'GH', name: 'Ghana', lat: 7.9, lng: -1.0 },
  { code: ' MA'.trim(), name: 'Morocco', lat: 31.8, lng: -7.1 },
  { code: 'ET', name: 'Ethiopia', lat: 9.1, lng: 40.5 },
  { code: 'TZ', name: 'Tanzania', lat: -6.4, lng: 34.9 },
  { code: 'IN', name: 'India', lat: 20.6, lng: 79.0 },
  { code: 'PK', name: 'Pakistan', lat: 30.4, lng: 69.3 },
  { code: 'BD', name: 'Bangladesh', lat: 23.7, lng: 90.4 },
  { code: 'LK', name: 'Sri Lanka', lat: 7.9, lng: 80.8 },
  { code: 'NP', name: 'Nepal', lat: 28.4, lng: 84.1 },
  { code: 'CN', name: 'China', lat: 35.9, lng: 104.2 },
  { code: 'JP', name: 'Japan', lat: 36.2, lng: 138.3 },
  { code: 'KR', name: 'South Korea', lat: 35.9, lng: 127.8 },
  { code: 'TW', name: 'Taiwan', lat: 23.7, lng: 121.0 },
  { code: 'HK', name: 'Hong Kong', lat: 22.3, lng: 114.2 },
  { code: 'TH', name: 'Thailand', lat: 15.9, lng: 100.99 },
  { code: 'VN', name: 'Vietnam', lat: 14.1, lng: 108.3 },
  { code: 'PH', name: 'Philippines', lat: 12.9, lng: 121.8 },
  { code: 'ID', name: 'Indonesia', lat: -0.8, lng: 113.9 },
  { code: 'MY', name: 'Malaysia', lat: 4.2, lng: 101.98 },
  { code: 'SG', name: 'Singapore', lat: 1.35, lng: 103.8 },
  { code: 'AU', name: 'Australia', lat: -25.3, lng: 133.8 },
  { code: 'NZ', name: 'New Zealand', lat: -40.9, lng: 174.9 },
  { code: 'FJ', name: 'Fiji', lat: -17.7, lng: 178.1 },
]

export const COUNTRY_MAP = COUNTRIES.reduce((acc, c) => { acc[c.code] = c; return acc }, {})

export function flagEmoji(code) {
  if (!code || code.length !== 2) return '\uD83C\uDF0D'
  return code.toUpperCase().replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)))
}
